services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    ports:
      - "27020:27017"
    volumes:
      - mongo_data:/data/db

  app:
    build: .
    depends_on:
      - mongo
    ports:
      - "3008:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    env_file:
      - .env
    environment:
      # In Docker, refer to Mongo by service name
      - MONGODB_URI=mongodb://mongo:27017/qrcode
      - NEXTAUTH_URL=http://localhost:3008
      - NEXTAUTH_DEBUG=true
      # Ensure file watching works reliably inside containers
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    command: sh -c "npm run dev"

volumes:
  mongo_data:
